[package]
name = "withfeature"
version = "0.1.0"
edition = "2021"

[dependencies]
resvg = { version = "0.44", default-features = false, features = ["text"] }
tiny-skia = { version = "0.11" }

[features]
with-raster-images = ["resvg/raster-images"]